// Prueba de audio (archivos propios + síntesis) y gráficos (calidad, ajustes).
import { createRequire } from 'node:module';
const { chromium } = createRequire(import.meta.url)('playwright');
const [base = 'http://localhost:3123/', out = '.'] = process.argv.slice(2);
const browser = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--autoplay-policy=no-user-gesture-required'] });
const page = await browser.newPage({ viewport: { width: 1400, height: 850 } });
page.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') console.log('[console]', m.type(), m.text().slice(0, 200)); });
page.on('pageerror', (e) => console.log('[pageerror]', e.message, e.stack?.split('\n').slice(0, 4).join(' | ')));
await page.goto(base + '?q=bajo');
await page.waitForTimeout(1500);
await page.click('#btn-menu-settings');
await page.waitForTimeout(500);
await page.screenshot({ path: `${out}/av-01-settings.png` });
const st = await page.evaluate(async () => {
  const { sfx } = await import('./js/client/audio.js');
  await sfx.indexReady;
  await new Promise((r) => setTimeout(r, 800));
  return { files: sfx.files, ctx: sfx.ctx?.state, track: sfx.track?.url, seq: !!sfx.seq, mood: sfx.mood };
});
console.log('menu audio', JSON.stringify(st));
await page.click('#set-close');
await page.click('#btn-solo');
await page.waitForFunction(() => window.__pt3d?.game?.room, null, { timeout: 60000 });
await page.waitForFunction(() => window.__pt3d.game.room.phase === 'planning' && window.__pt3d.game.room.round >= 2, null, { timeout: 300000 });
await page.evaluate(() => window.__pt3d.game.engine.setQuality('alto', false));
await page.waitForTimeout(6000);
const st2 = await page.evaluate(async () => {
  const { sfx } = await import('./js/client/audio.js');
  const e = window.__pt3d.game.engine;
  sfx.play('click');
  sfx.cry('pikachu', 'pichu', 2);
  sfx.cry('charizard', 'charmander', 3);
  sfx.skill('fuego', 'blast');
  await new Promise((r) => setTimeout(r, 300));
  const buf = [...sfx.buffers.entries()].map(([k, p]) => [k, !!p.buffer]);
  return { mood: sfx.mood, track: sfx.track?.url, seq: !!sfx.seq, buf, quality: e.quality, post: e.post, shadows: e.renderer.shadowMap.enabled, glow: e.glow };
});
console.log('planning audio', JSON.stringify(st2));
await page.screenshot({ path: `${out}/av-02-planning-alto.png` });
await page.evaluate(() => window.__pt3d.game.engine.setQuality('bajo', false));
await page.evaluate(() => window.__pt3d.game.send({ t: 'ready', v: true }));
await page.waitForFunction(() => window.__pt3d.game.room.phase === 'combat', null, { timeout: 180000 });
await page.waitForTimeout(3000);
await page.evaluate(() => window.__pt3d.game.engine.setQuality('alto', false));
await page.waitForTimeout(5000);
const st3 = await page.evaluate(async () => { const { sfx } = await import('./js/client/audio.js'); return { mood: sfx.mood, track: sfx.track?.url, seq: !!sfx.seq }; });
console.log('combat audio', JSON.stringify(st3));
await page.screenshot({ path: `${out}/av-03-combat-alto.png` });
await page.evaluate(() => window.__pt3d.game.engine.setQuality('bajo'));
await page.waitForTimeout(800);
await page.screenshot({ path: `${out}/av-04-combat-bajo.png` });
await page.evaluate(() => window.__pt3d.game.engine.setQuality('alto'));
await page.click('#btn-settings');
await page.waitForTimeout(400);
await page.screenshot({ path: `${out}/av-05-settings-ingame.png` });
await browser.close();
